# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49f26643a08aef9e925962a3df7c9a61a9d3c125b319d2f697075e14ef89e19645f55afd1d770909a188f7234f6615874ef7b58f1cb08c4c316795baecc798fd

test:
  secret_key_base: 728cb3286a95dc5095b645c34d5a96ecf29713156c505f5139b550cba6a025187946696fef130fb9a06dea2d59081cce6a91b2113573f437a26633bbaeb7dd43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
